### ISSUE TITLE
Accessing last line in a file performs poorly

### ISSUE THREAD

**Issue by trevor-criblio** [paulsena/Cribl-Log-Collector-Interview#6]
Steps to reproduce:
1. Download and unzip https://github.com/logpai/loghub/blob/master/HDFS#hdfs_v1 into the configured directory for the service
2. Start the service
3. `curl -u cribl:password "http://localhost:8080/cribl/log/tail?filename=HDFS.log&numEntries=1"` (update the file name to match your uncompressed file)

Expected result: getting just the last entry would be nearly instantaneous - reading only the last line should be fairly performant

Actual result: locally for me, this takes about 7 seconds

I did note that successive queries are faster due to the caching you've implemented... however, this seems to be consuming significantly more memory than I would expect.
Here's a `top` capture from before performing the api call to tail the file:
![image](https://github.com/paulsena/Cribl-Log-Collector-Interview/assets/94069108/d35b8c0b-bcb7-4f24-a1fb-e4217fcea145)
and then again after:
![image](https://github.com/paulsena/Cribl-Log-Collector-Interview/assets/94069108/28fe6b92-c95b-47ef-9b73-3a6ac6947c24)

**Comment by paulsena** [comment]
Hey @trevor-criblio,

Thanks for the feedback! That is a good point. When I was brainstorming solutions for this I came up with a few. When implementing, I chose a trade-off for the streams approach for ease of readability, design, and coding. That trade off was to spend more of my time on enterprise design, web service design, error handling, for an integrations role. Relative to just reading the file line by line, it was an large time complexity savings and more so, after adding caching, so went with that trade-off initially.

However, I did come up with a more performant lower level byte seeking solution that I outlined in my original README documentation here: https://github.com/paulsena/Cribl-Log-Collector-Interview?tab=readme-ov-file#file-reading
It would start reading at a byte offset from the end, read line by line, and store in a buffer. Buffer would be a linked list as to pop off front and insert into back, for memory alloc/de-alloc efficiency and keep the FIFO item ordering.
Can definitely get more performance with this, especially less memory consumption due how streams chaining works.

I'm currently swapping out to implementation and should have an update today for you. I'll close the issue out here when resolved and ping Diane. Thanks!

**Comment by paulsena** [comment]
@trevor-criblio 

Created a lower level file watcher implementation that works with huge files with much more performance. It reads into the end of a file backwards, using a byte offset and buffer until we hit max entries to tail count. Tests show tailing 1.6 GB file tails in 2 ms and JVM 170 MB mem usage total.

- Created a file watcher interface and left the old streams implementation for posterity and comparison. Can switch out implementations easily.
- Unit tests are parameterized now so tests both file watcher implementations

**Comment by trevor-criblio** [comment]
Nice! Performance and resource usage looks much better now :)
