### ISSUE TITLE
Hyphens should be allowed in log names

### ISSUE THREAD

**Issue by trevor-criblio** [paulsena/Cribl-Log-Collector-Interview#7]
Trying to read in logs from a file within the `node_logs` directory from https://zenodo.org/records/8196385/files/HDFS_v2.zip?download=1 gives the following result:
```
> curl -u cribl:password "http://localhost:8080/cribl/log/tail?filename=hadoop-hdfs-datanode-mesos-01.log&numEntries=1"
{"type":"about:blank","title":"Bad Request","status":400,"detail":"File name or filter input is invalid. Only alphanumeric characters, numbers, spaces, and periods are allowed.","instance":"/cribl/log/tail"}
```

**Comment by trevor-criblio** [comment]
Hyphens are a common enough naming convention that it probably makes sense to include them in the allow list

**Comment by paulsena** [comment]
That's good feedback, thanks! I updated my RegEx in the validation to be more relaxed.

`Improvement: Relaxed security restrictions on allowed filenames. Only fail validation on forward / or backward \ slashes now. `
